const globalActionsTypes = {
  SAGA_SEND_TO_SAGA_PROCESS: "SAGA_SEND_TO_SAGA_PROCESS",
  SAGA_SEND_TO_SAGA_PROCESS_TAKE_EVERY: "SAGA_SEND_TO_SAGA_PROCESS_TAKE_EVERY",
  PASS_DATA: "PASS_DATA",
  PASS_DATA_CLEAR: "PASS_DATA_CLEAR",
  SET_ADD_TO_REDUX: "SET_ADD_TO_REDUX",
  GLOBAL_ADD_TO_REDUX: "GLOBAL_ADD_TO_REDUX",
  PROCESS_ACTIONS: "PROCESS_ACTIONS",
};

export default globalActionsTypes;
